version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: ${APP_NAME}_app
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./database/data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: ${APP_NAME}_mailpit
    restart: unless-stopped
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP Server
    environment:
      MP_SMTP_AUTH_ALLOW_INSECURE: "true"
      MP_SMTP_TLS: "false"
      MP_SMTP_AUTH_ACCEPT_ANY: "true" # Mailpit UI Port

volumes:
  ecomm_template_app:


x-logging:
  driver: "json-file"
